### ISSUE TITLE
Verify the uri provided conforms to the HTTP Request specs 

### ISSUE THREAD

**Issue by jfacorro** [inaka/shotgun#101]

**Comment by kennethlakin** [comment]
Oh, goodness. I feel so silly.

fetch_uri/1 *does* properly check to see if the passed-in URI starts with a "/" character.

It turns out that in the PoC that I put together to see if shotgun would be suitable for my project, I assembled the string that contained the URI, then put that string into another list. check_uri saw that the first element of the list it was handed was not a "/", but a one-item list, and -correctly- declared this to be an invalid URI.

gun and friends *did* properly handle this URI-contained-in-a-deep-list, so perhaps it might be nice to call lists:flatten before performing the check.  kennethlakin@80e323b contains the code to do just that.
