### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/shotgun#173]
See #172 comments.

**Comment by elbrujohalcon** [comment]
If it is found that the library requires a complete overhaul to work with newest versions of gun, cowlib, etc., we might as well decide to shut down support of this library altogether. If that's so, please update the README.md with that info and I'll gladly archive the repository.

**Comment by unix1** [comment]
The application itself would need to be updated from gun 1.0.0-pre.1 to 1.0 release which from then on are backward compatible, and which I can't imagine needing a complete rewrite.

Tests, on the other hand, may be a bit more involved because of (cowboy, cowlib, lasse) dependencies. But it should be reasonable.

**Comment by unix1** [comment]
Actually, it didn't end up being that bad at all, so I made the PR.
