### ISSUE TITLE
Removing sync from dependencies?

### ISSUE THREAD

**Issue by sata** [inaka/shotgun#63]
Does Shotgun rely on Sync to work?
If not, why is it included in deps?

**Comment by jfacorro** [comment]
@sata No, `shotgun` does not rely on `sync` to work. The only reason it's included is for testing in the shell, since the `TEST_DEPS` only get downloaded when running the `test` target we mistakenly added `sync` to `shotgun`'s deps. We should remove `sync` as a dep and find a way to make it work in the shell some other way. Thanks for pointing this out! A PR is always welcome :smile:.

**Comment by sata** [comment]
PR #64 
I don't have a good proposal for the -s sync since it depends quite a lot on how people set their dev envs up.. Perhaps fiddling around with ~/.erlang? to add a path to sync and start it? :)

**Comment by jfacorro** [comment]
@sata Thanks for the PR. The ideal situation would be to remove `sync` as a dependency *and* have `sync` available when starting the shell. I think upgrading to the latest version of `erlang.mk` would do the trick since it now includes a `shell` target and a `SHELL_DEPS` configuration variable. For the additional options when starting the shell there's the `SHELL_OPTS` variable.

So after updating `erlang.mk` the `Makefile` in `shotgun` can loose the `shell` target and just define the following variables: 

```
CONFIG = rel/test.config

SHELL_DEPS = sync
dep_sync = git git://github.com/rustyio/sync.git master

SHELL_OPTS = -name ${PROJECT}@`hostname` -s ${PROJECT} -config ${CONFIG} -s sync
```

**Comment by sata** [comment]
Agreed, I wasn't ware of the new target, it does solve the issue.

I've updated the PR.

**Comment by jfacorro** [comment]
@sata Awesome, PR merged. Thanks!
